# Generated by Django 2.1 on 2018-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alarmdb',
            fields=[
                ('Index', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Time', models.DateField()),
                ('Level', models.CharField(max_length=100)),
                ('Info', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'NE40-Alarm',
            },
        ),
    ]
